
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET  http://localhost:3001/api/persons/64f99bf95d8bd47585314a94

###

DELETE http://localhost:3001/api/persons/64f9d3544f30c644893f972d

###

POST http://localhost:3001/api/persons/
Content-type: application/json
{
    "name": "Krzysiek",
    "number": "99990000"
}

###

PUT http://localhost:3001/api/persons/64faec32787509dc4ef2d586
Content-type: application/json

{
    "name": "Krzysiek",
    "number": "34567"
}
